# Libvirt
LIBVIRT_PATH = '/var/lib/libvirt/'
LIBVIRT_IMAGE_PATH = LIBVIRT_PATH + 'images/'

# Nueva VM
VM_NAME = ""
VM_PATH = LIBVIRT_IMAGE_PATH + VM_NAME + '/'

RAM="1024"
VCPUS="1"
MACADDRESS=""

HOSTNAME = ""
IPADDRESS = ""
GATEWAY = ""
DNS = ""
USERNAME = "root"
SSHRSA = ""